#!/bin/sh

CONFIG_FILE="/usr/share/system-recovery/system-recovery.cfg"
ACTION_FILE="/opt/.recovery.action"

actions=`cat $CONFIG_FILE | sed -ne '/^action_handlers[[:space:]]*=[[:space:]]*{/,/}/ p' | sed -ne 's/[[:space:]]*\(.*\)[[:space:]]*=[[:space:]]*\".*/\1/ p'`

for a in ${actions}
do
	if [ "$a" = "${1}" ]
	then
		echo "${1}" > $ACTION_FILE
		echo "Action changed to ${1}"
		exit
	fi
done

echo "Action ${1} is not specified in configuration."
